<?php

/**
 * Tradução PT → EN para buscas em APIs de stock (Openverse, Pexels, Mixkit…).
 * Frases completas têm prioridade sobre palavras individuais.
 */
return [

    'phrases' => [
        'por do sol' => 'sunset',
        'pôr do sol' => 'sunset',
        'fim de tarde' => 'sunset',
        'de noite' => 'night',
        'a noite' => 'night',
        'ao amanhecer' => 'sunrise',
        'de manha' => 'morning',
        'de manhã' => 'morning',
        'a tarde' => 'afternoon',
        'escritorio' => 'office',
        'escritório' => 'office',
        'video game' => 'gaming',
        'videogame' => 'gaming',
        'mercado financeiro' => 'stock market',
        'inteligencia artificial' => 'artificial intelligence',
        'inteligência artificial' => 'artificial intelligence',
        'rede social' => 'social media',
        'redes sociais' => 'social media',
        'celular' => 'smartphone',
        'telefone celular' => 'smartphone',
        'arvore' => 'tree',
        'árvore' => 'tree',
        'campo de futebol' => 'football field',
        'sala de aula' => 'classroom',
        'equipe de trabalho' => 'teamwork',
        'trabalho em equipe' => 'teamwork',
        'mae e filho' => 'mother and child',
        'mãe e filho' => 'mother and child',
        'pai e filho' => 'father and child',
        'casal feliz' => 'happy couple',
        'comida saudavel' => 'healthy food',
        'comida saudável' => 'healthy food',
        'fast food' => 'fast food',
        'chuva forte' => 'heavy rain',
        'dia chuvoso' => 'rainy day',
        'céu estrelado' => 'starry sky',
        'ceu estrelado' => 'starry sky',
    ],

    'words' => [
        // natureza
        'natureza' => 'nature', 'floresta' => 'forest', 'mata' => 'forest', 'selva' => 'jungle',
        'praia' => 'beach', 'mar' => 'ocean', 'oceano' => 'ocean', 'rio' => 'river',
        'lago' => 'lake', 'cachoeira' => 'waterfall', 'montanha' => 'mountain', 'serra' => 'mountain',
        'deserto' => 'desert', 'campo' => 'field', 'pasto' => 'meadow', 'jardim' => 'garden',
        'flor' => 'flower', 'flores' => 'flowers', 'arvore' => 'tree', 'árvore' => 'tree',
        'arvores' => 'trees', 'árvores' => 'trees', 'folha' => 'leaf', 'folhas' => 'leaves',
        'grama' => 'grass', 'terra' => 'earth', 'pedra' => 'stone', 'areia' => 'sand',
        'rocha' => 'rock', 'ilha' => 'island', 'vale' => 'valley', 'colina' => 'hill',
        'neve' => 'snow', 'gelo' => 'ice', 'fogo' => 'fire', 'fumaça' => 'smoke', 'fumaca' => 'smoke',
        'vento' => 'wind', 'tempestade' => 'storm', 'trovao' => 'thunder', 'trovão' => 'thunder',
        'raio' => 'lightning', 'arco' => 'rainbow', 'iríris' => 'rainbow', 'iridis' => 'rainbow',
        'ceu' => 'sky', 'céu' => 'sky', 'nuvem' => 'cloud', 'nuvens' => 'clouds',
        'sol' => 'sun', 'lua' => 'moon', 'estrela' => 'star', 'estrelas' => 'stars',
        'aurora' => 'aurora', 'entardecer' => 'sunset', 'amanhecer' => 'sunrise', 'noite' => 'night',
        'dia' => 'day', 'manha' => 'morning', 'manhã' => 'morning', 'tarde' => 'afternoon',
        'chuva' => 'rain', 'neblina' => 'fog', 'bruma' => 'mist',

        // animais
        'animal' => 'animal', 'animais' => 'animals', 'cachorro' => 'dog', 'cao' => 'dog', 'cão' => 'dog',
        'gato' => 'cat', 'passaro' => 'bird', 'pássaro' => 'bird', 'passaros' => 'birds',
        'peixe' => 'fish', 'peixes' => 'fish', 'cavalo' => 'horse', 'vaca' => 'cow',
        'boi' => 'ox', 'porco' => 'pig', 'ovelha' => 'sheep', 'cabra' => 'goat',
        'coelho' => 'rabbit', 'rato' => 'rat', 'macaco' => 'monkey', 'elefante' => 'elephant',
        'leao' => 'lion', 'leão' => 'lion', 'tigre' => 'tiger', 'urso' => 'bear',
        'lobo' => 'wolf', 'raposa' => 'fox', 'veado' => 'deer', 'girafa' => 'giraffe',
        'zebra' => 'zebra', 'panda' => 'panda', 'tubarao' => 'shark', 'tubarão' => 'shark',
        'baleia' => 'whale', 'golfinho' => 'dolphin', 'tartaruga' => 'turtle',
        'borboleta' => 'butterfly', 'abelha' => 'bee', 'formiga' => 'ant', 'inseto' => 'insect',
        'aranha' => 'spider', 'cobra' => 'snake', 'lagarto' => 'lizard', 'sapo' => 'frog',
        'galinha' => 'chicken', 'pato' => 'duck', 'coruja' => 'owl', 'aguia' => 'eagle', 'águia' => 'eagle',
        'pombo' => 'pigeon', 'beija' => 'hummingbird', 'colibri' => 'hummingbird',

        // cidade / arquitetura
        'cidade' => 'city', 'urbano' => 'urban', 'rua' => 'street', 'estrada' => 'road',
        'avenida' => 'avenue', 'ponte' => 'bridge', 'predio' => 'building', 'prédio' => 'building',
        'predios' => 'buildings', 'prédios' => 'buildings', 'casa' => 'house', 'casas' => 'houses',
        'apartamento' => 'apartment', 'condominio' => 'condominium', 'condomínio' => 'condominium',
        'escritorio' => 'office', 'escritório' => 'office', 'loja' => 'shop', 'mercado' => 'market',
        'shopping' => 'mall', 'aeroporto' => 'airport', 'estacao' => 'station', 'estação' => 'station',
        'metro' => 'subway', 'trem' => 'train', 'onibus' => 'bus', 'ônibus' => 'bus',
        'carro' => 'car', 'carros' => 'cars', 'moto' => 'motorcycle', 'motocicleta' => 'motorcycle',
        'bicicleta' => 'bicycle', 'bike' => 'bike', 'caminhao' => 'truck', 'caminhão' => 'truck',
        'barco' => 'boat', 'navio' => 'ship', 'iate' => 'yacht', 'aviao' => 'airplane', 'avião' => 'airplane',
        'helicoptero' => 'helicopter', 'helicóptero' => 'helicopter', 'trafego' => 'traffic', 'trânsito' => 'traffic',
        'farol' => 'lighthouse', 'castelo' => 'castle', 'igreja' => 'church', 'templo' => 'temple',
        'monumento' => 'monument', 'estatua' => 'statue', 'estátua' => 'statue', 'fonte' => 'fountain',
        'parque' => 'park', 'praca' => 'square', 'praça' => 'square', 'calçada' => 'sidewalk',
        'calcada' => 'sidewalk', 'bairro' => 'neighborhood', 'centro' => 'downtown',
        'horizonte' => 'skyline', 'paisagem' => 'landscape', 'paisagem' => 'landscape',

        // pessoas
        'pessoa' => 'person', 'pessoas' => 'people', 'homem' => 'man', 'mulher' => 'woman',
        'menino' => 'boy', 'menina' => 'girl', 'crianca' => 'child', 'criança' => 'child',
        'criancas' => 'children', 'crianças' => 'children', 'bebe' => 'baby', 'bebê' => 'baby',
        'familia' => 'family', 'família' => 'family', 'casal' => 'couple', 'amigos' => 'friends',
        'amigo' => 'friend', 'grupo' => 'group', 'multidao' => 'crowd', 'multidão' => 'crowd',
        'publico' => 'audience', 'público' => 'audience', 'rosto' => 'face', 'rostos' => 'faces',
        'mao' => 'hand', 'mão' => 'hand', 'maos' => 'hands', 'mãos' => 'hands', 'olhos' => 'eyes',
        'sorriso' => 'smile', 'feliz' => 'happy', 'triste' => 'sad', 'raiva' => 'angry',
        'medo' => 'fear', 'surpresa' => 'surprise', 'amor' => 'love', 'beijo' => 'kiss',
        'abraco' => 'hug', 'abraço' => 'hug', 'danca' => 'dance', 'dança' => 'dance',
        'corrida' => 'running', 'correr' => 'running', 'caminhada' => 'walking', 'exercicio' => 'exercise',
        'exercício' => 'exercise', 'yoga' => 'yoga', 'meditacao' => 'meditation', 'meditação' => 'meditation',
        'trabalho' => 'work', 'trabalhador' => 'worker', 'empregado' => 'employee',
        'chefe' => 'boss', 'reuniao' => 'meeting', 'reunião' => 'meeting', 'escritorio' => 'office',
        'medico' => 'doctor', 'médico' => 'doctor', 'enfermeira' => 'nurse', 'professor' => 'teacher',
        'aluno' => 'student', 'estudante' => 'student', 'engenheiro' => 'engineer',
        'advogado' => 'lawyer', 'policial' => 'police', 'bombeiro' => 'firefighter',
        'agricultor' => 'farmer', 'cozinheiro' => 'chef', 'garcom' => 'waiter', 'garçom' => 'waiter',

        // esportes / jogos
        'esporte' => 'sport', 'esportes' => 'sports', 'futebol' => 'football', 'soccer' => 'soccer',
        'basquete' => 'basketball', 'volei' => 'volleyball', 'vôlei' => 'volleyball',
        'tenis' => 'tennis', 'tênis' => 'tennis', 'natacao' => 'swimming', 'natação' => 'swimming',
        'surfe' => 'surfing', 'surf' => 'surf', 'skate' => 'skateboard', 'ciclismo' => 'cycling',
        'boxe' => 'boxing', 'luta' => 'fight', 'artes' => 'martial', 'marciais' => 'arts',
        'jogo' => 'game', 'jogos' => 'games', 'gaming' => 'gaming', 'videogame' => 'videogame',
        'console' => 'console', 'jogador' => 'gamer', 'xadrez' => 'chess', 'corrida' => 'race',
        'automobilismo' => 'racing', 'formula' => 'formula', 'gol' => 'goal', 'bola' => 'ball',
        'estadio' => 'stadium', 'estádio' => 'stadium', 'torcida' => 'fans', 'campeonato' => 'championship',

        // comida
        'comida' => 'food', 'alimento' => 'food', 'refeicao' => 'meal', 'refeição' => 'meal',
        'café' => 'coffee', 'cafe' => 'coffee', 'cha' => 'tea', 'chá' => 'tea',
        'suco' => 'juice', 'agua' => 'water', 'água' => 'water', 'cerveja' => 'beer',
        'vinho' => 'wine', 'pizza' => 'pizza', 'hamburguer' => 'burger', 'hambúrguer' => 'burger',
        'sanduiche' => 'sandwich', 'sanduíche' => 'sandwich', 'salada' => 'salad',
        'fruta' => 'fruit', 'frutas' => 'fruits', 'verdura' => 'vegetable', 'legume' => 'vegetable',
        'legumes' => 'vegetables', 'carne' => 'meat', 'frango' => 'chicken', 'peixe' => 'fish',
        'arroz' => 'rice', 'feijao' => 'beans', 'feijão' => 'beans', 'pao' => 'bread', 'pão' => 'bread',
        'bolo' => 'cake', 'doce' => 'candy', 'chocolate' => 'chocolate', 'sorvete' => 'ice cream',
        'restaurante' => 'restaurant', 'cozinha' => 'kitchen', 'chef' => 'chef', 'cozinhar' => 'cooking',

        // tech / negócios
        'tecnologia' => 'technology', 'tech' => 'tech', 'computador' => 'computer',
        'computadores' => 'computers', 'laptop' => 'laptop', 'notebook' => 'laptop',
        'celular' => 'smartphone', 'smartphone' => 'smartphone', 'tablet' => 'tablet',
        'internet' => 'internet', 'rede' => 'network', 'dados' => 'data', 'codigo' => 'code',
        'código' => 'code', 'programacao' => 'programming', 'programação' => 'programming',
        'software' => 'software', 'hardware' => 'hardware', 'servidor' => 'server',
        'nuvem' => 'cloud', 'inteligencia' => 'intelligence', 'inteligência' => 'intelligence',
        'artificial' => 'artificial', 'robotica' => 'robotics', 'robótica' => 'robotics',
        'robo' => 'robot', 'robô' => 'robot', 'drone' => 'drone', 'camera' => 'camera', 'câmera' => 'camera',
        'video' => 'video', 'vídeo' => 'video', 'filme' => 'movie', 'cinema' => 'cinema',
        'musica' => 'music', 'música' => 'music', 'som' => 'sound', 'audio' => 'audio',
        'microfone' => 'microphone', 'fone' => 'headphones', 'fones' => 'headphones',
        'negocio' => 'business', 'negócio' => 'business', 'empresa' => 'company',
        'corporativo' => 'corporate', 'financeiro' => 'finance', 'dinheiro' => 'money',
        'moeda' => 'currency', 'banco' => 'bank', 'investimento' => 'investment',
        'grafico' => 'chart', 'gráfico' => 'chart', 'crescimento' => 'growth',
        'sucesso' => 'success', 'startup' => 'startup', 'empreendedor' => 'entrepreneur',
        'marketing' => 'marketing', 'vendas' => 'sales', 'cliente' => 'customer',
        'contrato' => 'contract', 'aperto' => 'handshake', 'maos' => 'hands',

        // abstratos / mood
        'abstrato' => 'abstract', 'textura' => 'texture', 'padrao' => 'pattern', 'padrão' => 'pattern',
        'cor' => 'color', 'cores' => 'colors', 'vermelho' => 'red', 'azul' => 'blue',
        'verde' => 'green', 'amarelo' => 'yellow', 'laranja' => 'orange', 'roxo' => 'purple',
        'rosa' => 'pink', 'preto' => 'black', 'branco' => 'white', 'cinza' => 'gray',
        'dourado' => 'gold', 'prata' => 'silver', 'luz' => 'light', 'escuro' => 'dark',
        'sombra' => 'shadow', 'reflexo' => 'reflection', 'espelho' => 'mirror',
        'tempo' => 'time', 'relógio' => 'clock', 'relogio' => 'clock', 'calendario' => 'calendar',
        'calendário' => 'calendar', 'futuro' => 'future', 'passado' => 'past',
        'energia' => 'energy', 'poder' => 'power', 'forca' => 'strength', 'força' => 'strength',
        'paz' => 'peace', 'guerra' => 'war', 'liberdade' => 'freedom', 'esperanca' => 'hope',
        'esperança' => 'hope', 'sonho' => 'dream', 'viagem' => 'travel', 'turismo' => 'tourism',
        'ferias' => 'vacation', 'férias' => 'vacation', 'aventura' => 'adventure',
        'exploracao' => 'exploration', 'exploração' => 'exploration', 'mapa' => 'map',
        'mundo' => 'world', 'globo' => 'globe', 'planeta' => 'planet', 'espaco' => 'space',
        'espaço' => 'space', 'universo' => 'universe', 'galaxia' => 'galaxy', 'galáxia' => 'galaxy',
        'foguete' => 'rocket', 'astronauta' => 'astronaut', 'lua' => 'moon', 'marte' => 'mars',

        // saúde / ciência
        'saude' => 'health', 'saúde' => 'health', 'hospital' => 'hospital', 'clinica' => 'clinic',
        'clínica' => 'clinic', 'medicina' => 'medicine', 'remedio' => 'medicine', 'remédio' => 'medicine',
        'vacina' => 'vaccine', 'laboratorio' => 'laboratory', 'laboratório' => 'laboratory',
        'ciencia' => 'science', 'ciência' => 'science', 'quimica' => 'chemistry', 'química' => 'chemistry',
        'biologia' => 'biology', 'fisica' => 'physics', 'física' => 'physics', 'matematica' => 'math',
        'matemática' => 'math', 'microscopio' => 'microscope', 'microscópio' => 'microscope',
        'dna' => 'dna', 'celula' => 'cell', 'célula' => 'cell', 'virus' => 'virus', 'vírus' => 'virus',

        // festas / eventos
        'festa' => 'party', 'celebracao' => 'celebration', 'celebração' => 'celebration',
        'aniversario' => 'birthday', 'aniversário' => 'birthday', 'casamento' => 'wedding',
        'natal' => 'christmas', 'pascoa' => 'easter', 'páscoa' => 'easter',
        'carnaval' => 'carnival', 'halloween' => 'halloween', 'ano' => 'year', 'novo' => 'new',
        'fogos' => 'fireworks', 'balao' => 'balloon', 'balão' => 'balloon', 'presente' => 'gift',

        // construção / indústria
        'construcao' => 'construction', 'construção' => 'construction', 'obra' => 'construction',
        'engenharia' => 'engineering', 'fabrica' => 'factory', 'fábrica' => 'factory',
        'industria' => 'industry', 'indústria' => 'industry', 'maquina' => 'machine',
        'máquina' => 'machine', 'ferramenta' => 'tool', 'ferramentas' => 'tools',
        'madeira' => 'wood', 'metal' => 'metal', 'aco' => 'steel', 'aço' => 'steel',
        'plastico' => 'plastic', 'plástico' => 'plastic', 'vidro' => 'glass',
        'pintura' => 'painting', 'desenho' => 'drawing', 'arte' => 'art', 'artista' => 'artist',
        'escultura' => 'sculpture', 'museu' => 'museum', 'galeria' => 'gallery',
        'livro' => 'book', 'livros' => 'books', 'leitura' => 'reading', 'escola' => 'school',
        'universidade' => 'university', 'faculdade' => 'college', 'biblioteca' => 'library',
    ],

];
