<?php

return [
    'default_platform' => 'youtube_landscape',

    'platforms' => [
        'youtube_landscape' => [
            'name' => 'YouTube',
            'icon' => '▶',
            'aspect' => '16:9',
            'export_preset' => 'youtube_landscape',
            'filename' => 'thumbnail_youtube.jpg',
            'hint' => '1280×720 ou 1920×1080 — capa do vídeo horizontal',
        ],
        'youtube_shorts' => [
            'name' => 'YouTube Shorts',
            'icon' => '▲',
            'aspect' => '9:16',
            'export_preset' => 'youtube_shorts',
            'filename' => 'thumbnail_shorts.jpg',
            'hint' => '1080×1920 — vertical curto',
        ],
        'tiktok' => [
            'name' => 'TikTok',
            'icon' => '♪',
            'aspect' => '9:16',
            'export_preset' => 'tiktok',
            'filename' => 'thumbnail_tiktok.jpg',
            'hint' => '1080×1920 — capa vertical',
        ],
        'instagram_reels' => [
            'name' => 'Reels',
            'icon' => '◎',
            'aspect' => '9:16',
            'export_preset' => 'instagram_reels',
            'filename' => 'thumbnail_reels.jpg',
            'hint' => '1080×1920 — Instagram Reels',
        ],
        'instagram_stories' => [
            'name' => 'Stories',
            'icon' => '◉',
            'aspect' => '9:16',
            'export_preset' => 'instagram_stories',
            'filename' => 'thumbnail_stories.jpg',
            'hint' => '1080×1920 — Stories',
        ],
        'instagram_feed_square' => [
            'name' => 'Feed quadrado',
            'icon' => '□',
            'aspect' => '1:1',
            'export_preset' => 'instagram_feed_square',
            'filename' => 'thumbnail_feed.jpg',
            'hint' => '1080×1080 — post quadrado',
        ],
    ],

    'fonts' => [
        // —— Destaque YouTube / thumbnails ——
        ['slug' => 'impact', 'label' => 'Impact', 'group' => 'Destaque', 'file' => 'C:\\Windows\\Fonts\\impact.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],
        ['slug' => 'arial_black', 'label' => 'Arial Black', 'group' => 'Destaque', 'file' => 'C:\\Windows\\Fonts\\ariblk.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],
        ['slug' => 'franklin', 'label' => 'Franklin Gothic', 'group' => 'Destaque', 'file' => 'C:\\Windows\\Fonts\\framd.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],
        ['slug' => 'trebuchet_bold', 'label' => 'Trebuchet MS Bold', 'group' => 'Destaque', 'file' => 'C:\\Windows\\Fonts\\trebucbd.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],
        ['slug' => 'bahnschrift', 'label' => 'Bahnschrift', 'group' => 'Destaque', 'file' => 'C:\\Windows\\Fonts\\bahnschrift.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],
        ['slug' => 'segoe_bold', 'label' => 'Segoe UI Bold', 'group' => 'Destaque', 'file' => 'C:\\Windows\\Fonts\\segoeuib.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],

        // —— Sans-serif modernas ——
        ['slug' => 'arial', 'label' => 'Arial', 'group' => 'Sans-serif', 'file' => 'C:\\Windows\\Fonts\\arial.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'],
        ['slug' => 'arial_bold', 'label' => 'Arial Bold', 'group' => 'Sans-serif', 'file' => 'C:\\Windows\\Fonts\\arialbd.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],
        ['slug' => 'segoe', 'label' => 'Segoe UI', 'group' => 'Sans-serif', 'file' => 'C:\\Windows\\Fonts\\segoeui.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'],
        ['slug' => 'segoe_semilight', 'label' => 'Segoe UI Semilight', 'group' => 'Sans-serif', 'file' => 'C:\\Windows\\Fonts\\segoeuisl.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'],
        ['slug' => 'calibri', 'label' => 'Calibri', 'group' => 'Sans-serif', 'file' => 'C:\\Windows\\Fonts\\calibri.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'],
        ['slug' => 'calibri_bold', 'label' => 'Calibri Bold', 'group' => 'Sans-serif', 'file' => 'C:\\Windows\\Fonts\\calibrib.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],
        ['slug' => 'verdana', 'label' => 'Verdana', 'group' => 'Sans-serif', 'file' => 'C:\\Windows\\Fonts\\verdana.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'],
        ['slug' => 'verdana_bold', 'label' => 'Verdana Bold', 'group' => 'Sans-serif', 'file' => 'C:\\Windows\\Fonts\\verdanab.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],
        ['slug' => 'tahoma', 'label' => 'Tahoma', 'group' => 'Sans-serif', 'file' => 'C:\\Windows\\Fonts\\tahoma.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'],
        ['slug' => 'tahoma_bold', 'label' => 'Tahoma Bold', 'group' => 'Sans-serif', 'file' => 'C:\\Windows\\Fonts\\tahomabd.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],
        ['slug' => 'trebuchet', 'label' => 'Trebuchet MS', 'group' => 'Sans-serif', 'file' => 'C:\\Windows\\Fonts\\trebuc.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'],
        ['slug' => 'corbel', 'label' => 'Corbel', 'group' => 'Sans-serif', 'file' => 'C:\\Windows\\Fonts\\corbel.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'],
        ['slug' => 'corbel_bold', 'label' => 'Corbel Bold', 'group' => 'Sans-serif', 'file' => 'C:\\Windows\\Fonts\\corbelb.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],

        // —— Serif / editorial ——
        ['slug' => 'georgia', 'label' => 'Georgia', 'group' => 'Serif', 'file' => 'C:\\Windows\\Fonts\\georgia.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf'],
        ['slug' => 'georgia_bold', 'label' => 'Georgia Bold', 'group' => 'Serif', 'file' => 'C:\\Windows\\Fonts\\georgiab.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf'],
        ['slug' => 'times', 'label' => 'Times New Roman', 'group' => 'Serif', 'file' => 'C:\\Windows\\Fonts\\times.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf'],
        ['slug' => 'times_bold', 'label' => 'Times Bold', 'group' => 'Serif', 'file' => 'C:\\Windows\\Fonts\\timesbd.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf'],
        ['slug' => 'cambria', 'label' => 'Cambria', 'group' => 'Serif', 'file' => 'C:\\Windows\\Fonts\\cambriab.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf'],
        ['slug' => 'constantia', 'label' => 'Constantia', 'group' => 'Serif', 'file' => 'C:\\Windows\\Fonts\\constan.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf'],
        ['slug' => 'constantia_bold', 'label' => 'Constantia Bold', 'group' => 'Serif', 'file' => 'C:\\Windows\\Fonts\\constanb.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf'],

        // —— Pop / criativo (Ei Nerd, quadrinhos) ——
        ['slug' => 'comic', 'label' => 'Comic Sans MS', 'group' => 'Pop & criativo', 'file' => 'C:\\Windows\\Fonts\\comic.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'],
        ['slug' => 'comic_bold', 'label' => 'Comic Sans Bold', 'group' => 'Pop & criativo', 'file' => 'C:\\Windows\\Fonts\\comicbd.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],
        ['slug' => 'gabriola', 'label' => 'Gabriola (decorativa)', 'group' => 'Pop & criativo', 'file' => 'C:\\Windows\\Fonts\\Gabriola.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf'],
        ['slug' => 'ink_freehand', 'label' => 'Ink Freehand', 'group' => 'Pop & criativo', 'file' => 'C:\\Windows\\Fonts\\Inkfree.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'],

        // —— Tech / código (Código Fonte TV) ——
        ['slug' => 'consolas', 'label' => 'Consolas', 'group' => 'Tech & código', 'file' => 'C:\\Windows\\Fonts\\consola.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'],
        ['slug' => 'consolas_bold', 'label' => 'Consolas Bold', 'group' => 'Tech & código', 'file' => 'C:\\Windows\\Fonts\\consolab.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf'],
        ['slug' => 'courier', 'label' => 'Courier New', 'group' => 'Tech & código', 'file' => 'C:\\Windows\\Fonts\\cour.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'],
        ['slug' => 'courier_bold', 'label' => 'Courier Bold', 'group' => 'Tech & código', 'file' => 'C:\\Windows\\Fonts\\courbd.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf'],
        ['slug' => 'source_code_bold', 'label' => 'Source Code Pro Bold', 'group' => 'Tech & código', 'file' => 'C:\\Windows\\Fonts\\SourceCodePro-Bold.ttf', 'unix' => '/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf'],
    ],

    'defaults' => [
        'template' => 'youtube_pro',
        'platform_preset' => 'youtube_landscape',
        'image_source' => 'slide',
        'custom_image_path' => null,
        'slide_index' => 0,
        'title_text' => '',
        'subtitle_text' => '',
        'title_color' => '#ffffff',
        'subtitle_color' => '#f4f4f5',
        'accent_color' => '#ef4444',
        'accent_opacity' => 0,
        'background_color' => '#09090b',
        'background_opacity' => 0,
        'font_family' => 'impact',
        'title_size' => 72,
        'subtitle_size' => 34,
        'brightness' => 0,
        'contrast' => 5,
        'overlay_opacity' => 50,
        'text_align' => 'left',
        'vertical_align' => 'bottom',
    ],

    'templates' => [
        'youtube_pro' => [
            'name' => 'YouTube Pro',
            'description' => 'Estilo creator: faixa inferior, título grande à esquerda',
            'layout' => 'youtube_pro',
            'category' => 'profissional',
        ],
        'magazine' => [
            'name' => 'Capa revista',
            'description' => 'Editorial premium com degradê forte e tipografia bold',
            'layout' => 'magazine',
            'category' => 'profissional',
        ],
        'neon_burst' => [
            'name' => 'Neon impacto',
            'description' => 'Título com brilho e contraste alto — ideal para gaming/tech',
            'layout' => 'neon_burst',
            'category' => 'profissional',
        ],
        'news_breaking' => [
            'name' => 'Breaking news',
            'description' => 'Faixa vermelha superior + manchete — notícias e urgência',
            'layout' => 'news_breaking',
            'category' => 'profissional',
        ],
        'podcast_studio' => [
            'name' => 'Podcast / talk',
            'description' => 'Split elegante com bloco sólido e foto lateral',
            'layout' => 'podcast_studio',
            'category' => 'profissional',
        ],
        'vertical_hero' => [
            'name' => 'Hero vertical',
            'description' => 'Otimizado 9:16 — texto na base, ideal Shorts/Reels/TikTok',
            'layout' => 'vertical_hero',
            'category' => 'vertical',
        ],
        'square_clean' => [
            'name' => 'Quadrado clean',
            'description' => 'Minimal 1:1 para feed — foco total no título',
            'layout' => 'square_clean',
            'category' => 'quadrado',
        ],
        'spotlight' => [
            'name' => 'Spotlight',
            'description' => 'Vinheta dramática com texto central iluminado',
            'layout' => 'spotlight',
            'category' => 'profissional',
        ],
        'gradient_mesh' => [
            'name' => 'Gradient mesh',
            'description' => 'Degradê duplo moderno sobre a foto',
            'layout' => 'gradient_mesh',
            'category' => 'profissional',
        ],
        'badge_title' => [
            'name' => 'Badge título',
            'description' => 'Etiqueta colorida atrás do título — alta legibilidade',
            'layout' => 'badge_title',
            'category' => 'profissional',
        ],
        'classic' => [
            'name' => 'Clássico',
            'description' => 'Overlay escuro e texto centralizado',
            'layout' => 'overlay_center',
            'category' => 'básico',
        ],
        'cinematic' => [
            'name' => 'Cinematográfico',
            'description' => 'Letterbox + vinheta suave',
            'layout' => 'letterbox',
            'category' => 'básico',
        ],
        'split' => [
            'name' => 'Split colorido',
            'description' => 'Imagem + painel lateral com cor de destaque',
            'layout' => 'split_right',
            'category' => 'básico',
        ],
        'minimal' => [
            'name' => 'Só cor sólida',
            'description' => 'Sem foto — fundo sólido e tipografia',
            'layout' => 'solid',
            'category' => 'básico',
        ],
        'image_studio_final' => [
            'name' => 'Image Studio (arte final)',
            'description' => 'Usa a arte exportada do Image Studio sem reprocessar molduras ou textos',
            'layout' => 'image_studio_final',
            'category' => 'image_studio',
        ],
    ],
];
